version: "3.7"

services:
  nextjs:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - strapi
  strapi:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - '1337:1337'
    volumes:
      - /app/node_modules
      - ./server:/app
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx/dev
    ports:
      - '80:80'
      - '443:443'
    links:
      - nextjs
      - strapi
    restart: always
