export const REQUEST_AUTH = 'REQUEST_AUTH'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGOUT = 'LOGOUT'

export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const LOAD_AVATAR = 'LOAD_AVATAR'
export const DELETE_AVATAR = 'DELETE_AVATAR'

export const UPDATE_LIBRARY_CARDS_USER = 'UPDATE_LIBRARY_CARDS_USER'
export const UPDATE_ASSETS_USER = 'UPDATE_ASSETS_USER'

export const CREATE_TEXTURES_USER = 'CREATE_TEXTURES_USER'
export const CREATE_MATERIALS_USER = 'CREATE_MATERIALS_USER'
export const CREATE_ENVIRONMENTS_USER = 'CREATE_ENVIRONMENTS_USER'

export const UPDATE_TEXTURES_USER = 'UPDATE_TEXTURES_USER'
export const UPDATE_MATERIALS_USER = 'UPDATE_MATERIALS_USER'
export const UPDATE_MODELS_USER = 'UPDATE_MODELS_USER'
export const UPDATE_ENVIRONMENTS_USER = 'UPDATE_ENVIRONMENTS_USER'
