export const SET_OPEN_SIDEBAR = 'SET_OPEN_SIDEBAR'
export const SET_CHANGE_PROFILELAYOUT = 'SET_CHANGE_PROFILELAYOUT'
export const SET_OPEN_MENU = 'SET_OPEN_MENU'

export const CREATE_CARD_LIBRARY_DATA = 'CREATE_CARD_LIBRARY_DATA'
export const CHANGE_CARD_LIBRARY_DATA = 'CHANGE_CARD_LIBRARY_DATA'
export const GET_FAVORITES_CARD_LIBRARY_DATA = 'GET_FAVORITES_CARD_LIBRARY_DATA'

export const ADD_FILTERED_CHIP_DATA = 'ADD_FILTERED_CHIP_DATA'
export const DELETE_FILTERED_CHIP_DATA = 'DELETE_FILTERED_CHIP_DATA'
export const CLEAR_FILTERED_CHIP_LIST = 'CLEAR_FILTERED_CHIP_LIST'
export const UPDATE_FILTERED_CATEGORY_CHIP_DATA =
  'UPDATE_FILTERED_CATEGORY_CHIP_DATA'

export const CREATE_CARD_FAVORITE_DATA = 'CREATE_CARD_FAVORITE_DATA'
export const ADD_FAVORITE_CARD = 'ADD_FAVORITE_CARD'
export const DELETE_FAVORITE_CARD = 'DELETE_FAVORITE_CARD'

export const SET_CURRENT_CARD = 'SET_CURRENT_CARD'
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP'
export const INIT_SAVED_CARD = 'INIT_SAVED_CARD'
export const CREATE_SAVED_CARD = 'CREATE_SAVED_CARD'
export const DELETE_SAVED_CARD = 'DELETE_SAVED_CARD'
